---
applicationsets:
  default:
    namespace: argocd
    goTemplate: true
    generators:
      - git:
          repoURL: https://bitbucket.otlabs.fr/scm/pcr/azure-connectivity-stg-app-uttobi1.git
          revision: master
          directories:
            - path: "*"
    template:
      metadata:
        name: '{{.path.basename}}'
      spec:
        ignoreApplicationDifferences:
          - jsonPointers:
              - /spec/syncPolicy
        project: default
        source:
          repoURL: https://bitbucket.otlabs.fr/scm/pcr/azure-connectivity-stg-app-uttobi1.git
          targetRevision: master
          path: '{{.path.path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: '{{.path.basename}}'
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
        revisionHistoryLimit: 0