apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-azure-connectivity-stg-app-uttobi1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://bitbucket.otlabs.fr/scm/pcr/azure-connectivity-stg-app-uttobi1.git
  username: l.kubera@oberthur.com
  password: xxxxxxx